[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:tailscaled]
command=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/tailscaled.err.log
stdout_logfile=/var/log/supervisor/tailscaled.out.log
user=root